name: Add Mentioned Issues to Project Board

on:
  issues:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
      - edited


jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue mentions you
        id: check_mention
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            const username = 'mianzg'; // Replace with your GitHub username
            const issue = context.payload.issue;
            const comment = context.payload.comment;

            // Function to check if a string contains the username
            if (
              issue.title.includes(`@${username}`) ||
              issue.body.includes(`@${username}`)
            ) {
              return true;
            }

            if (comment && comment.body.includes(`@${username}`)) {
              return true;
            }

            return false;
      - name: Add Issue to Project Board
        if: steps.check_mention.outputs.result == 'true'
        uses: actions/add-to-project@v0.5.0
        with:
            # URL of the project to add issues to
            project-url: https://github.com/orgs/openwashdata-dev/projects/1
            # A GitHub personal access token with write access to the project
            github-token: ${{ secrets.WORKFLOW_TOKEN }}
            # A comma-separated list of labels to use as a filter for issue to be added
      
