name: Add Mentioned Issues to Project Board

on:
  issues:
    types:
      - opened
      - edited

jobs:
  add-issue-to-project:
    runs-on: ubuntu-latest

    steps:
      - name: Check if issue mentions you
        id: check_mention
        run: echo "Mentioned: ${{ contains(github.event.issue.body, '@mianzg') }}"

      - name: Add Issue to Project Board
        if: steps.check_mention.outputs.mention == 'true'
        uses: actions/add-to-project@v0.5.0
        with:
            # URL of the project to add issues to
            project-url: https://github.com/orgs/openwashdata-dev/projects/1
            # A GitHub personal access token with write access to the project
            github-token: ${{ secrets.WORKFLOW_TOKEN }}
            # A comma-separated list of labels to use as a filter for issue to be added
            
